---
- name: Compilar c贸digo fuente
  hosts: squid_compile
  become: true
  tasks:
    - name: Descargar c贸digo fuente
      ansible.builtin.get_url:
        url: "{{ src_url }}"
        dest: "/tmp/squid.tar.gz"
      
    - name: Extraer ficheros
      ansible.builtin.unarchive:
        src: "/tmp/squid.tar.gz"
        dest: "/tmp/"
        mode: "0644"
        owner: root
        group: root
        remote_src: true
        list_files: true
      register: result_file
    
    - name: Definir variable de directorio de c贸digo fuente
      set_fact:
        build_dir_path: "/tmp/{{ result_file.get('files') | first }}"

    - name: Dar permisos de ejecuci贸n a scripts necesarios
      ansible.builtin.file:
        path: "{{ build_dir_path }}/configure"
        mode: "0744"

    - name: Ejecutar ./configure con flags definidos
      ansible.builtin.command: ./configure {{ squid_configure_flags | join(' ') }}
      args:
        chdir: "{{ build_dir_path }}"
    
    - name: Compilar
      ansible.builtin.command: "make -j {{ compilation_process_number }}"
      args:
        chdir: "{{ build_dir_path }}"
    
    - name: Instalar
      ansible.builtin.command: make install
      args:
        chdir: "{{ build_dir_path }}"
    
    - name: Crear servicio en systemd para squid
      ansible.builtin.copy:
        src: "{{ build_dir_path }}/tools/systemd/squid.service"
        dest: "/etc/systemd/system/squid.service"
        remote_src: true
    
    - name: "Modificar servicio: crear directorio modificaciones"
      ansible.builtin.file:
        dest: /etc/systemd/system/squid.service.d/
        state: directory
        mode: "0764"
    
    - name: "Modificar servicio: crear overide de configuraciones"
      ansible.builtin.copy:
        src: "10-override.conf"
        dest: /etc/systemd/system/squid.service.d/10-override.conf

    - name: Crear servicio squid
      ansible.builtin.systemd_service:
        name: squid
        enabled: yes
        state: "started"