---
- name: Preparacion inicial
  hosts: all
  become: yes

  tasks:
    - name: Instalar dependencias necesarias
      ansible.builtin.apt:
        name:
          - logrotate
          - acl
          - attr
          - autoconf
          - bison
          - nettle-dev
          - build-essential
          - libacl1-dev
          - libaio-dev
          - libattr1-dev
          - libblkid-dev
          - libbsd-dev
          - libcap2-dev
          - libcppunit-dev
          - libldap2-dev
          - pkg-config
          - libxml2-dev
          - libdb-dev
          - libgnutls28-dev
          - openssl
          - devscripts
          - fakeroot
          - libdbi-perl
          - libssl-dev
          - libcppunit-dev
          - libecap3-dev
          - libkrb5-dev
          - comerr-dev
          - libnetfilter-conntrack-dev
          - libpam0g-dev
          - libsasl2-dev
          - krb5-user
          - msktutil
          - libsasl2-modules-gssapi-mit
          - libtdb-dev
        state: present
        update_cache: yes

    - name: Crear usuario y grupo para Squid
      ansible.builtin.user:
        name: proxy
        group: proxy
        create_home: no
        shell: /usr/sbin/nologin
        system: yes
        state: present
    
    - name: Crear directorios necesarios para Squid
      ansible.builtin.file:
        path: "{{ item  }}"
        state: directory
        owner: proxy
        group: proxy
        mode: '0644'
      loop:
        - /var/spool/squid
        - /var/log/squid
        - /var/cache/squid
    
    - name: Descargar código fuente de Squid
      ansible.builtin.unarchive:
        src: "https://www.squid-cache.org/Versions/v7/squid-7.0.0-20250103-rb56774dd09.tar.gz"
        dest: "/tmp/squid"
        remote_src: true
        mode: "0644"
      register: result_file