---
- name: Preparación inicial
  hosts: squid_compile
  become: yes
  tasks:
    - name: Instalar dependencias necesarias
      ansible.builtin.apt:
        name:
          - logrotate
          - acl
          - attr
          - autoconf
          - bison
          - nettle-dev
          - build-essential
          - libacl1-dev
          - libaio-dev
          - libattr1-dev
          - libblkid-dev
          - libbsd-dev
          - libcap2-dev
          - libcppunit-dev
          - libldap2-dev
          - pkg-config
          - libxml2-dev
          - libdb-dev
          - libgnutls28-dev
          - openssl
          - devscripts
          - fakeroot
          - libdbi-perl
          - libssl-dev
          - libcppunit-dev
          - libecap3-dev
          - libkrb5-dev
          - comerr-dev
          - libnetfilter-conntrack-dev
          - libpam0g-dev
          - libsasl2-dev
          - krb5-user
          - msktutil
          - libsasl2-modules-gssapi-mit
          - libtdb-dev
        state: present
        update_cache: yes

    - name: Crear usuario y grupo para Squid
      ansible.builtin.user:
        name: proxy
        group: proxy
        create_home: no
        shell: /usr/sbin/nologin
        system: yes
        state: present
    
    - name: Crear directorios necesarios para Squid
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: proxy
        group: proxy
        mode: '0764'
      loop:
        - /var/spool/squid
        - /var/log/squid
        - /var/cache/squid